version: '3.7'
services:
  oildatabase:
    container_name: oildatabase
    image: postgres:latest
    env_file:
      - .env
    volumes:
      - "${OILDB_VOL}:/var/lib/postgresql/data:rw"
    logging:
      options:
        max-size: 10m
        max-file: "3"
    networks:
      - oilnet
    ports:
      - ${PORT}:${PORT}

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    env_file:
      - .env
    networks:
      - oilnet
    ports:
      - ${HOSTPORT}:${LOCALPORT}

networks:
  oilnet:
    name: oilnet
    external: true
